title: 학습 정리
description: 주차별 학습 내용 정리
theme: minima
baseurl: ""
url: "https://juwon8891.github.io"

# RSS 비활성화
plugins:
  - jekyll-feed

# Feed 비활성화
feed:
  disable: true

markdown: kramdown
permalink: /:year/:month/:day/:title/

# Mermaid 지원
kramdown:
  syntax_highlighter_opts:
    disable: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
